const fs = require('fs');
const path = require('path');
const { copyHookScripts, removeHookScripts } = require('./hookAdapter');

const HOOK_SCRIPTS_DIR_NAME = 'hooks';
const PLUGINS_DIR_NAME = 'plugins';
const PLUGIN_FILE_NAME = 'evolver.js';
const EVOLVER_MARKER = '<!-- evolver-evolution-memory -->';
// First line of the plugin file. Used to (a) prove the plugin file is one we
// wrote, so uninstall can safely delete it, and (b) skip overwriting if the
// user replaced it with a custom plugin.
const PLUGIN_HEADER = '// _evolver_managed: true (do not remove this line)';

function buildPluginSource(hooksDirAbsolute) {
  // The plugin shells out to the same three Node scripts that every other
  // evolver adapter uses, so the runtime behavior stays consistent across
  // hosts. opencode loads .js files synchronously at startup and invokes
  // the default-exported async factory with a context object.
  return `${PLUGIN_HEADER}
// Auto-generated by \`evolver setup-hooks --platform=opencode\`.
// See https://opencode.ai/docs/plugins/ for the plugin API.
//
// This plugin wires opencode events to the three evolver hook scripts:
//   session.created      -> evolver-session-start.js  (inject memory)
//   tool.execute.after   -> evolver-signal-detect.js  (detect signals on writes/edits)
//   session.idle         -> evolver-session-end.js    (record outcome)
//
// Each script is a stdin/stdout JSON filter -- nothing else is shared with
// opencode, so removing this file fully detaches evolver from opencode.

const { spawnSync } = require('node:child_process');
const path = require('node:path');

const HOOKS_DIR = ${JSON.stringify(hooksDirAbsolute)};

function runHook(scriptName, payload, timeoutMs) {
  try {
    const result = spawnSync('node', [path.join(HOOKS_DIR, scriptName)], {
      input: JSON.stringify(payload || {}),
      encoding: 'utf8',
      timeout: timeoutMs,
    });
    if (!result || !result.stdout) return {};
    try { return JSON.parse(result.stdout); } catch { return {}; }
  } catch {
    return {};
  }
}

const Evolver = async () => ({
  event: async ({ event }) => {
    if (!event || typeof event.type !== 'string') return;
    if (event.type === 'session.created') {
      runHook('evolver-session-start.js', {
        session_id: event.properties && event.properties.info && event.properties.info.id,
      }, 3000);
      return;
    }
    if (event.type === 'session.idle') {
      runHook('evolver-session-end.js', {
        session_id: event.properties && event.properties.sessionID,
      }, 8000);
    }
  },
  'tool.execute.after': async (input, output) => {
    if (!input || typeof input.tool !== 'string') return;
    if (input.tool !== 'write' && input.tool !== 'edit') return;
    runHook('evolver-signal-detect.js', {
      tool_input: (output && output.args) || {},
      tool_response: (output && output.output) || (output && output.result) || {},
    }, 2000);
  },
});

module.exports = { Evolver };
module.exports.default = Evolver;
`;
}

function buildAgentsMdSection() {
  return `${EVOLVER_MARKER}
## Evolution Memory (Evolver)

This project uses evolver for self-evolution. Hooks automatically:
1. Inject recent evolution memory at session start
2. Detect evolution signals during file edits
3. Record outcomes at session end

For substantive tasks, call \`gep_recall\` before work and \`gep_record_outcome\` after.
Signals: log_error, perf_bottleneck, user_feature_request, capability_gap, deployment_issue, test_failure.`;
}

function appendSectionToFile(filePath, marker, content) {
  let existing = '';
  try { existing = fs.readFileSync(filePath, 'utf8'); } catch { /* new file */ }
  if (existing.includes(marker)) return false;
  const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n\n' : '\n';
  fs.writeFileSync(filePath, existing + separator + content + '\n', 'utf8');
  return true;
}

function isEvolverManagedPluginFile(filePath) {
  try {
    if (!fs.existsSync(filePath)) return false;
    const raw = fs.readFileSync(filePath, 'utf8');
    return raw.includes('_evolver_managed: true');
  } catch {
    return false;
  }
}

function writePluginFile(pluginsDir, source) {
  fs.mkdirSync(pluginsDir, { recursive: true });
  const dest = path.join(pluginsDir, PLUGIN_FILE_NAME);
  const tmp = dest + '.tmp';
  fs.writeFileSync(tmp, source, 'utf8');
  fs.renameSync(tmp, dest);
  return dest;
}

function install({ configRoot, evolverRoot, force }) {
  const opencodeDir = path.join(configRoot, '.opencode');
  const hooksDir = path.join(opencodeDir, HOOK_SCRIPTS_DIR_NAME);
  const pluginsDir = path.join(opencodeDir, PLUGINS_DIR_NAME);
  const pluginPath = path.join(pluginsDir, PLUGIN_FILE_NAME);
  const agentsMdPath = path.join(configRoot, 'AGENTS.md');

  if (!force && isEvolverManagedPluginFile(pluginPath)) {
    console.log('[opencode] Evolver plugin already installed. Use --force to overwrite.');
    return { ok: true, skipped: true };
  }

  fs.mkdirSync(opencodeDir, { recursive: true });

  const written = writePluginFile(pluginsDir, buildPluginSource(hooksDir));
  console.log('[opencode] Wrote ' + written);

  const copied = copyHookScripts(hooksDir, path.join(evolverRoot, 'src', 'adapters'));
  console.log('[opencode] Copied ' + copied.length + ' hook scripts to ' + hooksDir);

  const injected = appendSectionToFile(agentsMdPath, EVOLVER_MARKER, buildAgentsMdSection());
  if (injected) {
    console.log('[opencode] Injected evolution section into ' + agentsMdPath);
  }

  console.log('[opencode] Installation complete.');
  console.log('[opencode] opencode auto-loads plugins from .opencode/plugins/ -- restart opencode to activate.');

  return {
    ok: true,
    platform: 'opencode',
    files: [written, agentsMdPath, ...copied],
  };
}

function uninstall({ configRoot }) {
  const opencodeDir = path.join(configRoot, '.opencode');
  const hooksDir = path.join(opencodeDir, HOOK_SCRIPTS_DIR_NAME);
  const pluginsDir = path.join(opencodeDir, PLUGINS_DIR_NAME);
  const pluginPath = path.join(pluginsDir, PLUGIN_FILE_NAME);
  const agentsMdPath = path.join(configRoot, 'AGENTS.md');

  let changed = false;

  if (isEvolverManagedPluginFile(pluginPath)) {
    try { fs.unlinkSync(pluginPath); changed = true; } catch { /* ignore */ }
  }

  const scripts = removeHookScripts(hooksDir);
  if (scripts > 0) changed = true;

  try {
    if (fs.existsSync(agentsMdPath)) {
      let content = fs.readFileSync(agentsMdPath, 'utf8');
      if (content.includes(EVOLVER_MARKER)) {
        const idx = content.indexOf(EVOLVER_MARKER);
        const nextSection = content.indexOf('\n## ', idx + EVOLVER_MARKER.length);
        const endIdx = nextSection !== -1 ? nextSection : content.length;
        content = content.slice(0, idx).trimEnd() + (nextSection !== -1 ? content.slice(endIdx) : '');
        fs.writeFileSync(agentsMdPath, content.trimEnd() + '\n', 'utf8');
        changed = true;
      }
    }
  } catch { /* ignore */ }

  console.log(changed
    ? '[opencode] Uninstalled evolver plugin and hooks.'
    : '[opencode] No evolver plugin found to uninstall.');

  return { ok: true, removed: changed };
}

module.exports = {
  install,
  uninstall,
  buildPluginSource,
  isEvolverManagedPluginFile,
  PLUGIN_FILE_NAME,
};
